### ISSUE TITLE
Docs clarification: when are the bookie odds for?

### ISSUE THREAD

**Issue by qqtrend** [jokecamp/FootballData#13]
In https://github.com/jokecamp/FootballData/tree/master/football-data.co.uk as well as match information there are the betting odds. But there is only one shown for each bookmaker, whereas the odds change over time. Is it possible to clarify when the odds shown were captured?

Oh! I just found it at the top of http://www.football-data.co.uk/matches.php !  So, can the below paragraph be added to the README.md (assuming it has been consistent for all the data history?):

Please note that the odds are collected for the downloadable weekend fixtures on Fridays afternoons not later than 17:00 British Standard Time. Odds for midweek fixtures are collected Tuesdays not later than 15:00 British Standard Time.

**Comment by jokecamp** [comment]
Done.

Added to https://github.com/jokecamp/FootballData/blob/master/football-data.co.uk/README.md
