### ISSUE TITLE
Wales.json missing

### ISSUE THREAD

**Issue by kwakuwulf** [jokecamp/FootballData#17]
Thanks for the great data set
I just saw that the json-file for Wales is empty!

Cheers

**Comment by jokecamp** [comment]
Good catch. I've added it.

Thanks!

**Comment by kwakuwulf** [comment]
Thanks for the quick respond. Great work!





Von: Joe Kampschmidt [mailto:notifications@github.com]
Gesendet: Dienstag, 7. Juni 2016 18:39
An: jokecamp/FootballData
Cc: Wolfgang Glatzl; Author
Betreff: Re: [jokecamp/FootballData] Wales.json missing (#17)


Good catch. I've added it.

Thanks!
