### ISSUE TITLE
Hi, is this still being maintained

### ISSUE THREAD

**Issue by rahulkadukar** [jokecamp/FootballData#45]
More of a question than an issue but is this being maintained. I would like to add a bunch of data for EPL and Championship.

**Comment by jokecamp** [comment]
I will accept any PR submitted for data. I don't have time myself for adding new data right now.

**Comment by rahulkadukar** [comment]
Ok, I will create a PR by this weekend. Will start with basic match data first and keep adding to it. Do you prefer JSON or YAML.

**Comment by jokecamp** [comment]
No preference. Just like consistency within the smaller sets.
